#!/usr/bin/env node

import * as crypto from "node:crypto";
import * as fs from "node:fs";
import * as path from "node:path";

import { OverlayCompiler } from "./core/overlayCompiler.js";
import { validateDrop } from "./core/validation/assetValidator.js";
import { createDropManifest } from "./factories/dropfactory.js";
import { buildOfferLadder } from "./marketplace/offerBuilder.js";
import { buildMarketReadyKit } from "./marketplace/marketReadyKit.js";
import { buildPackage } from "./packaging/packager.js";

async function main(): Promise<void> {
  const dropName = readArg("--drop", "AnarchI Signal Pack");
  const themeName = readArg("--theme", "Industrial Protocol");
  const intensity = Number.parseFloat(readArg("--intensity", "0.45"));
  const serialPrefix = readArg("--serial-prefix", "ANX");

  const manifest = createDropManifest(dropName, themeName);
  manifest.edition = intensity > 0 ? "corrupted" : "clean";
  manifest.corruptionProfile.enabled = intensity > 0;
  manifest.corruptionProfile.gridInstability = intensity * 0.5;
  manifest.corruptionProfile.signalNoise = intensity * 0.3;
  manifest.corruptionProfile.colorBleed = intensity * 0.8;
  manifest.corruptionProfile.frameRupture = intensity * 0.2;
  manifest.marketplace.title = `${dropName} - Deterministic Overlay Pack`;
  manifest.marketplace.shortDescription = "A market-ready deterministic visual system pack generated by AnarchI Visual Systems.";
  manifest.marketplace.longDescription = "Validated HTML/CSS visual assets with deterministic manifest metadata, sellable offer tiers, and checksum evidence.";
  manifest.marketplace.tags = ["overlay", "streaming", "deterministic", "brand-system", "anarchi"];
  manifest.assets = [
    { id: "starting_soon", name: "Starting Soon", type: "screen", width: 1920, height: 1080, enabled: true },
    { id: "brb", name: "Be Right Back", type: "screen", width: 1920, height: 1080, enabled: true },
    { id: "overlay", name: "Main Stream Overlay", type: "overlay", width: 1920, height: 1080, enabled: true },
    { id: "alerts", name: "Event Alerts", type: "widget", width: 800, height: 200, enabled: true },
  ];

  const seed = JSON.stringify({ dropName, themeName, intensity, serialPrefix });
  manifest.serialNumber = `${serialPrefix}-${crypto.createHash("sha256").update(seed).digest("hex").slice(0, 12).toUpperCase()}`;

  const root = path.join(process.cwd(), "dist", "market-ready");
  const assetOutput = path.join(root, "assets");
  const kitOutput = path.join(root, "kit");
  const releaseOutput = path.join(root, "release");
  await fs.promises.rm(root, { recursive: true, force: true });
  await fs.promises.mkdir(assetOutput, { recursive: true });
  await fs.promises.mkdir(kitOutput, { recursive: true });
  await fs.promises.mkdir(releaseOutput, { recursive: true });

  const compiledAssetDirectory = await new OverlayCompiler(assetOutput).compile(manifest);
  const validation = validateDrop(compiledAssetDirectory, manifest);
  if (!validation.valid) {
    throw new Error(`Market pack validation failed: ${validation.missingFiles.join(", ")}`);
  }

  const offers = buildOfferLadder(manifest);
  const kit = buildMarketReadyKit(manifest, offers, compiledAssetDirectory, kitOutput);
  const zipPath = await buildPackage({
    dropName: `${manifest.id}-market-ready`,
    sourceDirectory: root,
    outputDirectory: releaseOutput,
  });

  console.log(JSON.stringify({
    status: "market-ready",
    serialNumber: manifest.serialNumber,
    compiledAssetDirectory,
    kitDirectory: kit.kitDirectory,
    zipPath,
    offers: offers.map((offer) => ({ tier: offer.tier, sku: offer.sku, priceUsd: offer.priceUsd })),
  }, null, 2));
}

function readArg(name: string, fallback: string): string {
  const index = process.argv.indexOf(name);
  return index >= 0 ? process.argv[index + 1] ?? fallback : fallback;
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
